# Generated by Django 4.2.1 on 2023-06-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=200)),
                ('inscription', models.DateTimeField(verbose_name='Date inscription')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
            ],
        ),
    ]
